catalog/urls.py
# catalog/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # <- route chính của /catalog/
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path(
        'mybooks/',
        views.LoanedBooksByUserListView.as_view(),
        name='my-borrowed'),
    path(
        'book/<uuid:pk>/renew/',
        views.BookRenewView.as_view(),
        name='renew-book'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path(
        'author/<int:pk>/update/',
        views.AuthorUpdate.as_view(),
        name='author-update'),
    path(
        'author/<int:pk>/delete/',
        views.AuthorDelete.as_view(),
        name='author-delete'),
    path(
        'borrowed/',
        views.LoanedBooksAllListView.as_view(),
        name='all-borrowed'),
    path('authors/', views.AuthorListView.as_view(), name='author-list'),
    path(
        'author/<int:pk>/',
        views.AuthorDetailView.as_view(),
        name='author-detail'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('secureadmin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),  # <-- Gọi đến app catalog
    # <-- Chuyển / về /catalog/
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid
from datetime import date

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

from .constants import (
    GENRE_NAME_MAX_LENGTH,
    LANGUAGE_NAME_MAX_LENGTH,
    BOOK_TITLE_MAX_LENGTH,
    BOOK_SUMMARY_MAX_LENGTH,
    BOOK_ISBN_MAX_LENGTH,
    BOOKINSTANCE_IMPRINT_MAX_LENGTH,
    AUTHOR_FIRST_NAME_MAX_LENGTH,
    AUTHOR_LAST_NAME_MAX_LENGTH,
    LOAN_STATUS,
    LOAN_STATUS_MAINTENANCE,
    ISBN_HELP_TEXT,
)


class Genre(models.Model):
    name = models.CharField(
        max_length=GENRE_NAME_MAX_LENGTH,
        help_text=_('Enter a book genre (e.g. Science Fiction)')
    )

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(
        max_length=LANGUAGE_NAME_MAX_LENGTH,
        help_text=_(
            "Enter the book's natural language (e.g. English, Vietnamese)")
    )

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=AUTHOR_FIRST_NAME_MAX_LENGTH)
    last_name = models.CharField(max_length=AUTHOR_LAST_NAME_MAX_LENGTH)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(_('Died'), null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Book(models.Model):
    title = models.CharField(max_length=BOOK_TITLE_MAX_LENGTH)

    author = models.ForeignKey(
        Author,
        on_delete=models.SET_NULL,
        null=True
    )

    summary = models.TextField(
        max_length=BOOK_SUMMARY_MAX_LENGTH,
        help_text=_('Enter a brief description of the book')
    )

    isbn = models.CharField(
        _('ISBN'),
        max_length=BOOK_ISBN_MAX_LENGTH,
        unique=True,
        help_text=ISBN_HELP_TEXT
    )

    genre = models.ManyToManyField(
        Genre,
        help_text=_('Select a genre for this book')
    )

    language = models.ForeignKey(
        Language,
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text=_('Unique ID for this particular book across whole library')
    )
    book = models.ForeignKey(Book, on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=BOOKINSTANCE_IMPRINT_MAX_LENGTH)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True)

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default=LOAN_STATUS_MAINTENANCE,
        help_text=_('Book availability'),
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back

templates/base_generic.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
      {% block title %}{% trans "Local Library" %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          <ul class="sidebar-nav">
            <li>
              <a href="{% url 'index' %}">
                {% trans "Home" %}
              </a>
            </li>
            <li>
              <a href="{% url 'books' %}">
                {% trans "All books" %}
              </a>
            </li>
          </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10">
          {% block content %}{% endblock %}
          {% block pagination %}
          {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
              {% if page_obj.has_previous %}
              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                {% trans "previous" %}
              </a>
              {% endif %}
              <span class="page-current">
                {% blocktrans with current=page_obj.number total=page_obj.paginator.num_pages %}
                Page {{ current }} of {{ total }}.
                {% endblocktrans %}
              </span>
              {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                {% trans "next" %}
              </a>
              {% endif %}
            </span>
          </div>
          {% endif %}
          {% endblock %}
        </div>
      </div>
    </div>
    <ul class="sidebar-nav">
      {% if user.is_authenticated %}
      <li>
        {% trans "User:" %} {{ user.get_username }}
      </li>
      <li>
        <a href="{% url 'my-borrowed' %}">
          {% trans "My Borrowed" %}
        </a>
      </li>
      <li>
        <form action="{% url 'logout' %}" method="post" style="display: inline">
          {% csrf_token %}
          <button type="submit" class="btn btn-link p-0">
            {% trans "Logout" %}
          </button>
        </form>
      </li>
      {% else %}
      <li>
        <a href="{% url 'login' %}?next={{ request.path }}">
          {% trans "Login" %}
        </a>
      </li>
      {% endif %}
      {% if perms.catalog.can_mark_returned %}
      <li>
        <a href="{% url 'all-borrowed' %}">
          {% trans "All Borrowed" %}
        </a>
      </li>
      {% endif %}

      {% if perms.catalog.view_author %}
   <li><a href="{% url 'author-list' %}">{% trans "All authors" %}</a></li>
      {% endif %}
    </ul>
  </body>
</html>

templates/index.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "Local Library Home" %}</h1>
  <p>
    {% blocktrans %}
      Welcome to Locallibrary, a website developed by
      <em>Mozilla Developer Network</em>!
    {% endblocktrans %}
  </p>

  <h2>{% trans "Dynamic content" %}</h2>
  <p>{% trans "The library has the following record counts:" %}</p>
  <ul>
    <li><strong>{% trans "Books" %}:</strong> {{ num_books }}</li>
    <li><strong>{% trans "Copies" %}:</strong> {{ num_instances }}</li>
    <li>
      <strong>{% trans "Copies available" %}:</strong>
      {{ num_instances_available }}
    </li>
    <li><strong>{% trans "Authors" %}:</strong> {{ num_authors }}</li>
  </ul>

  {% blocktrans count num_visits=num_visits %}
    You have visited this page {{ num_visits }} time.
  {% plural %}
    You have visited this page {{ num_visits }} times.
  {% endblocktrans %}

{% endblock %}