catalog/urls.py
# catalog/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # <- route chính của /catalog/
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path(
        'mybooks/',
        views.LoanedBooksByUserListView.as_view(),
        name='my-borrowed'),
    path(
        'book/<uuid:pk>/renew/',
        views.BookRenewView.as_view(),
        name='renew-book'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path(
        'author/<int:pk>/update/',
        views.AuthorUpdate.as_view(),
        name='author-update'),
    path(
        'author/<int:pk>/delete/',
        views.AuthorDelete.as_view(),
        name='author-delete'),
    path(
        'borrowed/',
        views.LoanedBooksAllListView.as_view(),
        name='all-borrowed'),
    path('authors/', views.AuthorListView.as_view(), name='author-list'),
    path(
        'author/<int:pk>/',
        views.AuthorDetailView.as_view(),
        name='author-detail'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('secureadmin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),  # <-- Gọi đến app catalog
    # <-- Chuyển / về /catalog/
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid
from datetime import date

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

from .constants import (
    GENRE_NAME_MAX_LENGTH,
    LANGUAGE_NAME_MAX_LENGTH,
    BOOK_TITLE_MAX_LENGTH,
    BOOK_SUMMARY_MAX_LENGTH,
    BOOK_ISBN_MAX_LENGTH,
    BOOKINSTANCE_IMPRINT_MAX_LENGTH,
    AUTHOR_FIRST_NAME_MAX_LENGTH,
    AUTHOR_LAST_NAME_MAX_LENGTH,
    LOAN_STATUS,
    LOAN_STATUS_MAINTENANCE,
    ISBN_HELP_TEXT,
)


class Genre(models.Model):
    name = models.CharField(
        max_length=GENRE_NAME_MAX_LENGTH,
        help_text=_('Enter a book genre (e.g. Science Fiction)')
    )

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(
        max_length=LANGUAGE_NAME_MAX_LENGTH,
        help_text=_(
            "Enter the book's natural language (e.g. English, Vietnamese)")
    )

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=AUTHOR_FIRST_NAME_MAX_LENGTH)
    last_name = models.CharField(max_length=AUTHOR_LAST_NAME_MAX_LENGTH)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(_('Died'), null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Book(models.Model):
    title = models.CharField(max_length=BOOK_TITLE_MAX_LENGTH)

    author = models.ForeignKey(
        Author,
        on_delete=models.SET_NULL,
        null=True
    )

    summary = models.TextField(
        max_length=BOOK_SUMMARY_MAX_LENGTH,
        help_text=_('Enter a brief description of the book')
    )

    isbn = models.CharField(
        _('ISBN'),
        max_length=BOOK_ISBN_MAX_LENGTH,
        unique=True,
        help_text=ISBN_HELP_TEXT
    )

    genre = models.ManyToManyField(
        Genre,
        help_text=_('Select a genre for this book')
    )

    language = models.ForeignKey(
        Language,
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text=_('Unique ID for this particular book across whole library')
    )
    book = models.ForeignKey(Book, on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=BOOKINSTANCE_IMPRINT_MAX_LENGTH)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True)

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default=LOAN_STATUS_MAINTENANCE,
        help_text=_('Book availability'),
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from catalog.models import BookInstance

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text=_("Enter a date between today and 4 weeks (default 3)."),
        widget=forms.TextInput(attrs={'type': 'date'})
    )
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date – renewal in past'))
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date – more than 4 weeks ahead'))
        return data

class RenewBookModelForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between today and 4 weeks (default 3).')}
    def clean_due_back(self):
        data = self.cleaned_data['due_back']
        # same validations…
        return data

catalog/views.py
from datetime import (
    date,
    timedelta
)


from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from django.views.generic.edit import (
    UpdateView,
    CreateView,
    DeleteView
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from catalog.models import (
    Book,
    Author,
    BookInstance
)
from catalog.constants import (
    LOAN_STATUS_AVAILABLE,
    LOAN_STATUS_ON_LOAN,
    DEFAULT_RENEWAL_WEEKS,
    PAGINATION_BY,
    DEFAULT_DATE_OF_DEATH
)
from catalog.forms import RenewBookModelForm


def index(request):

    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_instances_available = BookInstance.objects.filter(
        status__exact=LOAN_STATUS_AVAILABLE
    ).count()
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0) + 1
    request.session['num_visits'] = num_visits

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context)


class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'catalog/book_list.html'
    paginate_by = PAGINATION_BY


class BookDetailView(generic.DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'catalog/book_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = self.get_object()
        context['genres'] = book.genre.all()
        context['instances'] = book.bookinstance_set.all()
        return context


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = PAGINATION_BY

    def get_queryset(self):
        return BookInstance.objects.filter(
            borrower=self.request.user, status__exact=LOAN_STATUS_ON_LOAN).order_by('due_back')


class BookRenewView(PermissionRequiredMixin, UpdateView):
    # Sử dụng Class-Based View (UpdateView) thay vì Function-Based View
    model = BookInstance
    form_class = RenewBookModelForm
    context_object_name = 'book_instance'
    template_name = 'catalog/book_renew_librarian.html'
    permission_required = 'catalog.can_mark_returned'
    success_url = reverse_lazy('my-borrowed')

    def get_initial(self):
        # propose a date DEFAULT_RENEWAL_WEEKS weeks from today
        return {
            'due_back': date.today() + timedelta(weeks=DEFAULT_RENEWAL_WEEKS)
        }


class AuthorListView(generic.ListView):
    model = Author
    template_name = 'catalog/author_list.html'
    context_object_name = 'author_list'
    paginate_by = PAGINATION_BY


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'catalog/author_detail.html'


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.add_author'
    initial = {'date_of_death': DEFAULT_DATE_OF_DEATH}


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.change_author'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    permission_required = 'catalog.delete_author'
    success_url = reverse_lazy('author-list')


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = PAGINATION_BY

    def get_queryset(self):
        return BookInstance.objects.filter(
            status__exact=LOAN_STATUS_ON_LOAN
        ).order_by('due_back')

templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %} {% load i18n %} {% block content %}
<h1>{% trans "Delete Author" %}</h1>
<p>
  {% blocktrans with name=object.get_full_name %} Are you sure you want to
  delete author {{ name }}? {% endblocktrans %}
</p>

<form method="post">
  {% csrf_token %}
  <button type="submit">{% trans "Yes, delete" %}</button>
</form>
{% endblock %}

templates/catalog/author_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>
    {{ object.first_name }} {{ object.last_name }}
  </h1>

  <p><strong>{% trans "Date of birth" %}:</strong>
     {{ object.date_of_birth }}</p>

  {% if object.date_of_death %}
    <p><strong>{% trans "Date of death" %}:</strong>
       {{ object.date_of_death }}</p>
  {% endif %}

  {% if perms.catalog.change_author %}
    <p>
      <a href="{% url 'author-update' object.pk %}">{% trans "Edit" %}</a>
      {% if perms.catalog.delete_author %}
        | <a href="{% url 'author-delete' object.pk %}">{% trans "Delete" %}</a>
      {% endif %}
    </p>
  {% endif %}
{% endblock %}

templates/catalog/author_form.html
{% extends "base_generic.html" %} {% load i18n %} {% block content %}
<h1>
  {% if object %} {% trans "Update Author" %} {% else %} 
  {% trans "Create Author" %} {% endif %}
</h1>

<form method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit">{% trans "Submit" %}</button>
</form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "All Authors" %}</h1>

  {# “Add new author” link for users who can add authors #}
  {% if perms.catalog.add_author %}
    <p>
      <a class="btn btn-primary" href="{% url 'author-create' %}">
        {% trans "Add new author" %}
      </a>
    </p>
  {% endif %}

  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          <a href="{% url 'author-detail' author.pk %}">
            {{ author.last_name }}, {{ author.first_name }}
          </a>
          {# Edit/Delete links as before #}
          {% if perms.catalog.change_author %}
            | <a href="{% url 'author-update' author.pk %}">{% trans "Edit" %}</a>
          {% endif %}
          {% if perms.catalog.delete_author %}
            | <a href="{% url 'author-delete' author.pk %}">{% trans "Delete" %}</a>
          {% endif %}
        </li>
      {% endfor %}
    </ul>

  {% else %}
    <p>{% trans "No authors found." %}</p>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load book_extras %}

{% block content %}
<h1>{% trans "Title" %}: {{ book.title }}</h1>

<p><strong>{% trans "Author" %}:</strong> <a href="">{{ book.author }}</a></p>

<p><strong>{% trans "Summary" %}:</strong> {{ book.summary }}</p>
<p><strong>{% trans "ISBN" %}:</strong> {{ book.isbn }}</p>
<p><strong>{% trans "Language" %}:</strong> {{ book.language }}</p>
<p><strong>{% trans "Genre" %}:</strong> {{ genres|join:", " }}</p>

<div class="book-copies-section">
  <h4>{% trans "Copies" %}</h4>

  {% for copy in instances %}
  <hr />
  <p class="{% get_status_class copy.status %}">{{ copy.get_status_display }}</p>
  {% if copy.status != 'a' %}
    <p><strong>{% trans "Due to be returned" %}:</strong> {{ copy.due_back }}</p>
  {% endif %}
  <p><strong>{% trans "Imprint" %}:</strong> {{ copy.imprint }}</p>
  <p class="text-muted"><strong>{% trans "Id" %}:</strong> {{ copy.id }}</p>
  {% endfor %}
</div>
{% endblock %}

templates/catalog/book_list.html
{% extends "base_generic.html" %} {% load i18n %} {% block content %}
<h1>{% trans "Book List" %}</h1>
{% if book_list %}
<ul>
  {% for book in book_list %}
  <li>
    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
    ({{book.author}})
  </li>
  {% endfor %}
</ul>
{% else %}
<p>{% trans "There are no books in the library." %}</p>
{% endif %} {% endblock %}

templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Renew:" %} {{ book_instance.book.title }}</h1>
    <p>{% trans "Borrower:" %} {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>
        {% trans "Due date:" %} {{ book_instance.due_back }}
    </p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="{% trans 'Submit' %}">
    </form>
{% endblock %}

templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}

<h1>{% trans "All Borrowed Books" %}</h1>

{% if bookinstance_list %}
<ul>
  {% for inst in bookinstance_list %}
    <li class="{% if inst.is_overdue %}text-danger{% endif %}">
      <a href="{% url 'book-detail' inst.book.pk %}">{{ inst.book.title }}</a>
      — {{ inst.borrower.username }} — {{ inst.due_back }}
      {% if perms.catalog.can_mark_returned %} |
        <a href="{% url 'renew-book' inst.pk %}">{% trans "Renew" %}</a>
      {% endif %}
    </li>
  {% endfor %}
</ul>

{% else %}
  <p>{% trans "There are no books currently on loan." %}</p>
{% endif %}

{% endblock %}

templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "My Borrowed Books" %}</h1>

  {% if bookinstance_list %}
    <ul>
      {% for inst in bookinstance_list %}
        <li class="{% if inst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' inst.book.pk %}">
            {{ inst.book.title }}
          </a> — {{ inst.due_back }}
        </li>
      {% endfor %}
    </ul>

  {% else %}
    <p>{% trans "You have no books on loan." %}</p>
  {% endif %}
{% endblock %}